In [30]:
from sklearn import naive_bayes
from sklearn import metrics
import pandas as pd
df=pd.read_csv("./DeployTennis2/play_tennis.csv")
df

    day   outlook  temp humidity    wind play
0    D1     Sunny   Hot     High    Weak   No
1    D2     Sunny   Hot     High  Strong   No
2    D3  Overcast   Hot     High    Weak  Yes
3    D4      Rain  Mild     High    Weak  Yes
4    D5      Rain  Cool   Normal    Weak  Yes
5    D6      Rain  Cool   Normal  Strong   No
6    D7  Overcast  Cool   Normal  Strong  Yes
7    D8     Sunny  Mild     High    Weak   No
8    D9     Sunny  Cool   Normal    Weak  Yes
9   D10      Rain  Mild   Normal    Weak  Yes
10  D11     Sunny  Mild   Normal  Strong  Yes
11  D12  Overcast  Mild     High  Strong  Yes
12  D13  Overcast   Hot   Normal    Weak  Yes
13  D14      Rain  Mild     High  Strong   No

In [31]:
to_drop=['day']
df.drop(to_drop,inplace=True,axis=1)

In [32]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
df['outlook']=le.fit_transform(df['outlook'])
df['temp']=le.fit_transform(df['temp'])
df['humidity']=le.fit_transform(df['humidity'])
df['wind']=le.fit_transform(df['wind'])
df['play']=le.fit_transform(df['play'])
df

    outlook  temp  humidity  wind  play
0         2     1         0     1     0
1         2     1         0     0     0
2         0     1         0     1     1
3         1     2         0     1     1
4         1     0         1     1     1
5         1     0         1     0     0
6         0     0         1     0     1
7         2     2         0     1     0
8         2     0         1     1     1
9         1     2         1     1     1
10        2     2         1     0     1
11        0     2         0     0     1
12        0     1         1     1     1
13        1     2         0     0     0

In [33]:
X=df.iloc[:,0:4].values
y=df.iloc[:,4].values
#X
y

array([0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0])

In [34]:
# model=naive_bayes.GaussianNB()
# model.fit(X, y)
# y_pred = model.predict(X)
# score = metrics.accuracy_score(y, y_pred)
# print("Akurasi dengan menggunakan Naive Bayes: ", score)

In [35]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size = 0.8)

In [36]:
nb = naive_bayes.GaussianNB()

nb.fit(X_train, y_train)
y_pred = nb.predict(X_test)
score = metrics.accuracy_score(y_test, y_pred)
print("Akurasi dengan menggunakan Naive Bayes: ", score)

Akurasi dengan menggunakan Naive Bayes:  0.6666666666666666